/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaces.dialogo;

import controle.ControladorCopiaFilme;
import javax.swing.JOptionPane;

/**
 *
 * @author juarez
 */
public class DialogRemoverCopiaFilme extends javax.swing.JDialog {
   private int idCopiaFilme;
   private ControladorCopiaFilme controlador;
   public boolean isRemoved;
   /**
    * Creates new form NewJDialog
    */
   public DialogRemoverCopiaFilme(boolean modal, int idCopiaFilme, ControladorCopiaFilme controlador) {
      super(new javax.swing.JFrame(), modal);
      this.idCopiaFilme = idCopiaFilme;
      this.controlador = controlador;
      initComponents();
      
      
      setVisible(true);      
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      buttonGroup = new javax.swing.ButtonGroup();
      tituloLabel = new javax.swing.JLabel();
      removerButton = new javax.swing.JButton();
      vendidaRadioButton = new javax.swing.JRadioButton();
      danificadaRadioButton = new javax.swing.JRadioButton();
      perdidaRadioButton = new javax.swing.JRadioButton();
      cancelarButton = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setModal(true);

      tituloLabel.setText("MOTIVO DE REMOÇÃO");

      removerButton.setText("Remover");
      removerButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            removerButtonActionPerformed(evt);
         }
      });

      buttonGroup.add(vendidaRadioButton);
      vendidaRadioButton.setText("Vendida");

      buttonGroup.add(danificadaRadioButton);
      danificadaRadioButton.setText("Danificada");

      buttonGroup.add(perdidaRadioButton);
      perdidaRadioButton.setText("Perdida");

      cancelarButton.setText("Cancelar");
      cancelarButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            cancelarButtonActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(39, 39, 39)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(perdidaRadioButton)
                  .addGap(18, 18, 18)
                  .addComponent(danificadaRadioButton)
                  .addGap(27, 27, 27)
                  .addComponent(vendidaRadioButton)
                  .addGap(0, 55, Short.MAX_VALUE))
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(tituloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(removerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(58, 58, 58)
            .addComponent(tituloLabel)
            .addGap(29, 29, 29)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(perdidaRadioButton)
               .addComponent(danificadaRadioButton)
               .addComponent(vendidaRadioButton))
            .addGap(35, 35, 35)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(removerButton)
               .addComponent(cancelarButton))
            .addContainerGap(23, Short.MAX_VALUE))
      );

      pack();
      setLocationRelativeTo(null);
   }// </editor-fold>//GEN-END:initComponents

   private void removerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerButtonActionPerformed
      if(isCamposVazio()){
         JOptionPane.showMessageDialog(this, "Selecione uma opção");
         return;
      }
      if(controlador.remover(idCopiaFilme)){
         JOptionPane.showMessageDialog(this, "Removido com sucesso");
         isRemoved = true;
         dispose();
      }
      else{
         JOptionPane.showMessageDialog(this, "Não foi possível remover cópia do filme");
         isRemoved = false;
         dispose();
      }
   }//GEN-LAST:event_removerButtonActionPerformed

   private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
      
      dispose();
   }//GEN-LAST:event_cancelarButtonActionPerformed
   
   private boolean isCamposVazio(){
      if(perdidaRadioButton.isSelected()||danificadaRadioButton.isSelected()||vendidaRadioButton.isSelected())
         return false;
      return true;
                 
   }
   
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.ButtonGroup buttonGroup;
   private javax.swing.JButton cancelarButton;
   private javax.swing.JRadioButton danificadaRadioButton;
   private javax.swing.JRadioButton perdidaRadioButton;
   private javax.swing.JButton removerButton;
   private javax.swing.JLabel tituloLabel;
   private javax.swing.JRadioButton vendidaRadioButton;
   // End of variables declaration//GEN-END:variables
}
