/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaces;

import controle.ControladorCadastroCliente;
import entidade.Cliente;
import entidade.Visao;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juarez
 */
public class JanelaCadastroClientes extends javax.swing.JDialog {
   public static Cliente clienteConsultado=null;
   ControladorCadastroCliente controlador;
   private enum Estado{inserindo, editando};
   Estado estado = null;
   int ponteiro;//aponta posição do limit do select
   int QUANTIDADE=10;
  
   public JanelaCadastroClientes(ControladorCadastroCliente controlador) {
      super(new javax.swing.JFrame(), true);
      estado = Estado.inserindo;
      this.controlador = controlador;
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      filtroButtonGroup = new javax.swing.ButtonGroup();
      cadastroClienteTabbedPane = new javax.swing.JTabbedPane();
      consultajPanel = new javax.swing.JPanel();
      cpfRadioButton = new javax.swing.JRadioButton();
      nomeRadioButton = new javax.swing.JRadioButton();
      pesquisaText = new javax.swing.JTextField();
      pesquisarButton = new javax.swing.JButton();
      jScrollPane3 = new javax.swing.JScrollPane();
      tabelaConsultaTable = new javax.swing.JTable();
      backButton = new javax.swing.JButton();
      nextButton = new javax.swing.JButton();
      quantidade_de_resultadosSpinner = new javax.swing.JSpinner();
      cadastroPanel = new javax.swing.JPanel();
      cadastroTextosPanel = new javax.swing.JPanel();
      telefonejLabel = new javax.swing.JLabel();
      enderecojLabel = new javax.swing.JLabel();
      enderecoText = new javax.swing.JTextField();
      nomejLabel = new javax.swing.JLabel();
      nomeText = new javax.swing.JTextField();
      cpfjLabel1 = new javax.swing.JLabel();
      cpfTextFormatted = new javax.swing.JFormattedTextField();
      telefoneTextFormatted = new javax.swing.JFormattedTextField();
      buttonsCadastroPanel = new javax.swing.JPanel();
      inserir_clienteButton = new javax.swing.JButton();
      remover_clienteButton = new javax.swing.JButton();
      salvar_clienteButton = new javax.swing.JButton();
      jPanel1 = new javax.swing.JPanel();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setTitle("Cadastro de Clientes");
      setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
      setName("cadastroCliente"); // NOI18N

      cadastroClienteTabbedPane.setBackground(new java.awt.Color(242, 241, 240));
      cadastroClienteTabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
      cadastroClienteTabbedPane.setToolTipText("");
      cadastroClienteTabbedPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
      cadastroClienteTabbedPane.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N

      consultajPanel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

      filtroButtonGroup.add(cpfRadioButton);
      cpfRadioButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
      cpfRadioButton.setText("cpf");

      filtroButtonGroup.add(nomeRadioButton);
      nomeRadioButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
      nomeRadioButton.setSelected(true);
      nomeRadioButton.setText("nome");
      nomeRadioButton.setToolTipText("");

      pesquisaText.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
      pesquisaText.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyReleased(java.awt.event.KeyEvent evt) {
            consultarPorCaracter(evt);
         }
      });

      pesquisarButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
      pesquisarButton.setText("Pesquisar");
      pesquisarButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            pesquisarButtonActionPerformed(evt);
         }
      });

      tabelaConsultaTable.setModel(construirTabela());
      tabelaConsultaTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
      tabelaConsultaTable.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            consultaClienteTable(evt);
         }
      });
      jScrollPane3.setViewportView(tabelaConsultaTable);

      backButton.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
      backButton.setText("<-");
      backButton.setEnabled(false);
      backButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            backConsulta(evt);
         }
      });

      nextButton.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
      nextButton.setText("->");
      nextButton.setEnabled(false);
      nextButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            nextConsulta(evt);
         }
      });

      quantidade_de_resultadosSpinner.setModel(new javax.swing.SpinnerNumberModel(10, 0, 30, 1));
      quantidade_de_resultadosSpinner.setValue(QUANTIDADE);

      javax.swing.GroupLayout consultajPanelLayout = new javax.swing.GroupLayout(consultajPanel);
      consultajPanel.setLayout(consultajPanelLayout);
      consultajPanelLayout.setHorizontalGroup(
         consultajPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jScrollPane3)
         .addGroup(consultajPanelLayout.createSequentialGroup()
            .addGap(57, 57, 57)
            .addComponent(pesquisaText, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
            .addGap(37, 37, 37)
            .addComponent(pesquisarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
            .addGap(63, 63, 63))
         .addGroup(consultajPanelLayout.createSequentialGroup()
            .addGroup(consultajPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(consultajPanelLayout.createSequentialGroup()
                  .addGap(89, 89, 89)
                  .addComponent(cpfRadioButton)
                  .addGap(33, 33, 33)
                  .addComponent(nomeRadioButton))
               .addGroup(consultajPanelLayout.createSequentialGroup()
                  .addGap(304, 304, 304)
                  .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(quantidade_de_resultadosSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(nextButton, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)))
            .addGap(336, 336, 336))
      );
      consultajPanelLayout.setVerticalGroup(
         consultajPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultajPanelLayout.createSequentialGroup()
            .addGap(34, 34, 34)
            .addGroup(consultajPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(cpfRadioButton)
               .addComponent(nomeRadioButton))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(consultajPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(pesquisaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(pesquisarButton))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(consultajPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(backButton)
               .addComponent(nextButton)
               .addComponent(quantidade_de_resultadosSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
      );

      cadastroClienteTabbedPane.addTab("   Consulta   ", consultajPanel);

      cadastroPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

      telefonejLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
      telefonejLabel.setText("telefone");

      enderecojLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
      enderecojLabel.setText("endereco");

      enderecoText.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

      nomejLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
      nomejLabel.setText("nome");

      nomeText.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
      nomeText.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyTyped(java.awt.event.KeyEvent evt) {
            inserir_só_letrasEVT(evt);
         }
      });

      cpfjLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
      cpfjLabel1.setText("cpf");

      try {
         cpfTextFormatted.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
      } catch (java.text.ParseException ex) {
         ex.printStackTrace();
      }
      cpfTextFormatted.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

      try {
         telefoneTextFormatted.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
      } catch (java.text.ParseException ex) {
         ex.printStackTrace();
      }
      telefoneTextFormatted.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

      javax.swing.GroupLayout cadastroTextosPanelLayout = new javax.swing.GroupLayout(cadastroTextosPanel);
      cadastroTextosPanel.setLayout(cadastroTextosPanelLayout);
      cadastroTextosPanelLayout.setHorizontalGroup(
         cadastroTextosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroTextosPanelLayout.createSequentialGroup()
            .addGap(48, 48, 48)
            .addGroup(cadastroTextosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(nomeText)
               .addComponent(telefoneTextFormatted)
               .addComponent(enderecoText)
               .addComponent(cpfTextFormatted, javax.swing.GroupLayout.Alignment.TRAILING)
               .addGroup(cadastroTextosPanelLayout.createSequentialGroup()
                  .addGroup(cadastroTextosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(telefonejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(enderecojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(nomejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(cpfjLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(0, 327, Short.MAX_VALUE)))
            .addContainerGap())
      );
      cadastroTextosPanelLayout.setVerticalGroup(
         cadastroTextosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(cadastroTextosPanelLayout.createSequentialGroup()
            .addGap(84, 84, 84)
            .addComponent(cpfjLabel1)
            .addGap(6, 6, 6)
            .addComponent(cpfTextFormatted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(35, 35, 35)
            .addComponent(nomejLabel)
            .addGap(6, 6, 6)
            .addComponent(nomeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(35, 35, 35)
            .addComponent(enderecojLabel)
            .addGap(6, 6, 6)
            .addComponent(enderecoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(35, 35, 35)
            .addComponent(telefonejLabel)
            .addGap(6, 6, 6)
            .addComponent(telefoneTextFormatted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      telefonejLabel.getAccessibleContext().setAccessibleParent(cadastroTextosPanel);
      enderecojLabel.getAccessibleContext().setAccessibleParent(cadastroTextosPanel);
      enderecoText.getAccessibleContext().setAccessibleParent(cadastroTextosPanel);
      nomejLabel.getAccessibleContext().setAccessibleParent(cadastroTextosPanel);
      nomeText.getAccessibleContext().setAccessibleParent(cadastroTextosPanel);
      cpfjLabel1.getAccessibleContext().setAccessibleParent(cadastroTextosPanel);
      cpfTextFormatted.getAccessibleContext().setAccessibleParent(cadastroTextosPanel);
      telefoneTextFormatted.getAccessibleContext().setAccessibleParent(cadastroTextosPanel);

      inserir_clienteButton.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
      inserir_clienteButton.setText("+");
      inserir_clienteButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            preparaInsercaoButton(evt);
         }
      });

      remover_clienteButton.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
      remover_clienteButton.setText("remover");
      remover_clienteButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            deletarCliente(evt);
         }
      });

      salvar_clienteButton.setBackground(javax.swing.UIManager.getDefaults().getColor("Nb.ScrollPane.Border.color"));
      salvar_clienteButton.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
      salvar_clienteButton.setText("Salvar");
      salvar_clienteButton.setActionCommand("");
      salvar_clienteButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            gravarCliente(evt);
         }
      });

      javax.swing.GroupLayout buttonsCadastroPanelLayout = new javax.swing.GroupLayout(buttonsCadastroPanel);
      buttonsCadastroPanel.setLayout(buttonsCadastroPanelLayout);
      buttonsCadastroPanelLayout.setHorizontalGroup(
         buttonsCadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonsCadastroPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(salvar_clienteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(35, 35, 35))
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonsCadastroPanelLayout.createSequentialGroup()
            .addGap(30, 30, 30)
            .addComponent(inserir_clienteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
            .addGap(63, 63, 63)
            .addComponent(remover_clienteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
            .addGap(57, 57, 57))
      );
      buttonsCadastroPanelLayout.setVerticalGroup(
         buttonsCadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonsCadastroPanelLayout.createSequentialGroup()
            .addContainerGap(29, Short.MAX_VALUE)
            .addGroup(buttonsCadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(remover_clienteButton)
               .addComponent(inserir_clienteButton))
            .addGap(18, 18, 18)
            .addComponent(salvar_clienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(20, 20, 20))
      );

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 101, Short.MAX_VALUE)
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 100, Short.MAX_VALUE)
      );

      javax.swing.GroupLayout cadastroPanelLayout = new javax.swing.GroupLayout(cadastroPanel);
      cadastroPanel.setLayout(cadastroPanelLayout);
      cadastroPanelLayout.setHorizontalGroup(
         cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(cadastroPanelLayout.createSequentialGroup()
            .addComponent(cadastroTextosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(buttonsCadastroPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addGroup(cadastroPanelLayout.createSequentialGroup()
                  .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(0, 0, Short.MAX_VALUE))))
      );
      cadastroPanelLayout.setVerticalGroup(
         cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(cadastroTextosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroPanelLayout.createSequentialGroup()
            .addGap(92, 92, 92)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(47, 47, 47)
            .addComponent(buttonsCadastroPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(115, Short.MAX_VALUE))
      );

      cadastroClienteTabbedPane.addTab("   Cadastro   ", null, cadastroPanel, "cadastrar clientes");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(cadastroClienteTabbedPane)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(cadastroClienteTabbedPane)
      );

      getAccessibleContext().setAccessibleName("");

      pack();
      setLocationRelativeTo(null);
   }// </editor-fold>//GEN-END:initComponents

   
   private void pesquisarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarButtonActionPerformed
      if((int)quantidade_de_resultadosSpinner.getValue()<0)
         return;
      backButton.setEnabled(false);
      nextButton.setEnabled(true);
      ponteiro=0;
      QUANTIDADE =(int)quantidade_de_resultadosSpinner.getValue();
      consultar(ponteiro,QUANTIDADE);
      nextButton.setEnabled(true);
      backButton.setEnabled(false);
      
   }//GEN-LAST:event_pesquisarButtonActionPerformed
   
   private void consultar(int min, int max){
      
      ArrayList<Cliente> clientes = new ArrayList();
      //se o botao radio cpf estiver marcado entao consulta cpf se não consulte por nome
      //lista todos os clientes de acordo com a entrada do usuario
      if (cpfRadioButton.isSelected()) {
         clientes = controlador.getClientes("cpf", pesquisaText.getText(),min, max);
      } else {
         clientes = controlador.getClientes("nome", pesquisaText.getText(), min, max);
      }
      //Chama método para imprimir clientes na tabela
      atualizarTabela(clientes);
   }
   
   private void preencherCamposText(Cliente cliente){
      
      nomeText.setText(cliente.getNome());
      cpfTextFormatted.setText(cliente.getCpf());
      enderecoText.setText(cliente.getEndereco());
      telefoneTextFormatted.setText(cliente.getTelefone());   
   }
   
   private void deletarCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarCliente
      if(estado==Estado.editando){
         if(controlador.deletarCliente(cpfTextFormatted.getText())){
            limpaCamposText();
            estado=Estado.inserindo;
         }
         
      }
      else{
         JOptionPane.showMessageDialog(null, "erro ao excluir cliente!");
      }

   }//GEN-LAST:event_deletarCliente

   private void preparaInsercaoButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preparaInsercaoButton
      cpfTextFormatted.setEnabled(true);
      limpaCamposText();
      
      estado = Estado.inserindo;
      
   }//GEN-LAST:event_preparaInsercaoButton

   private void gravarCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gravarCliente
      if (isCamposVazio()){
         JOptionPane.showMessageDialog(this, "Todos os campos precisam ser preenchidos, tente novamente!", "Informação", JOptionPane.INFORMATION_MESSAGE);
         return;
      }
      
      //cria objeto cliente apartir dos dados entrado pelo usuario
      Cliente cliente = new Cliente(cpfTextFormatted.getText(), nomeText.getText(), enderecoText.getText(), telefoneTextFormatted.getText());
      if(estado==Estado.inserindo){ // se modo estiver inserindo entao botao gravar tem que inserir novo cliente
         if(controlador.inserirCliente(cliente)){
            Visao<String> visao = cliente.getVisao();
            cpfTextFormatted.setEnabled(false);
            
         }
      }
      else controlador.alterarCliente(cliente);
      
      estado = Estado.editando;
      
   }//GEN-LAST:event_gravarCliente
   
   
   private void inserir_só_letrasEVT(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inserir_só_letrasEVT
      JanelaVideoLocadora.inserir_só_letrasEVT(evt);
   }//GEN-LAST:event_inserir_só_letrasEVT

   
   private void nextConsulta(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextConsulta
      if((int)quantidade_de_resultadosSpinner.getValue()<0)
         return;
      ponteiro+=QUANTIDADE;
      consultar(ponteiro,QUANTIDADE);
      backButton.setEnabled(true);
      if(tabelaConsultaTable.getRowCount()<QUANTIDADE)
         nextButton.setEnabled(false);
   }//GEN-LAST:event_nextConsulta

   private void backConsulta(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backConsulta
      if((int)quantidade_de_resultadosSpinner.getValue()<0||ponteiro<QUANTIDADE)
         return;
      ponteiro-=QUANTIDADE;
      consultar(ponteiro,QUANTIDADE);
      nextButton.setEnabled(true);
      if(ponteiro==0)
        backButton.setEnabled(false);
   }//GEN-LAST:event_backConsulta

   private void consultaClienteTable(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaClienteTable
      
      int linha_selecionada = -1;
      linha_selecionada = tabelaConsultaTable.getSelectedRow();//capita indice da linha que foi clicada
      
      if(linha_selecionada>=0){
         String cpfCliente = (String)tabelaConsultaTable.getValueAt(linha_selecionada, 1);//pega o cpf da tabela.
         Cliente cliente = controlador.getCliente(cpfCliente);//busca cliente com o mesmo cpf
         
         preencherCamposText(cliente); //preenche textFields da aba de cadastro
         
         //altera o modo para edição pois utilizara o mesmo botao de salvar. 
         estado = Estado.editando;
         cpfTextFormatted.setEnabled(false);//como esta editando campo de cpf nao podera sofrer alteraçao
         //troca de aba -- abre aba de cadastro
         cadastroClienteTabbedPane.setSelectedIndex(1); 
      }
   }//GEN-LAST:event_consultaClienteTable

   private void consultarPorCaracter(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_consultarPorCaracter
      pesquisarButtonActionPerformed(null);
   }//GEN-LAST:event_consultarPorCaracter

   private boolean isCamposVazio(){
      return cpfTextFormatted.getText().compareToIgnoreCase("   .   .   -  ")==0 || nomeText.getText().isEmpty() || 
              enderecoText.getText().isEmpty() ||  telefoneTextFormatted.getText().compareToIgnoreCase("(  )    -    ")==0;
   }
   
   private void limpaCamposText(){
      
      nomeText.setText("");
      cpfTextFormatted.setText("");
      enderecoText.setText("");
      telefoneTextFormatted.setText("");
      
      DefaultTableModel modelo = new DefaultTableModel();
      modelo.addColumn("ID");
      modelo.addColumn("NOME");
      modelo.addColumn("CPF");
      modelo.addColumn("FONE");
      modelo.addColumn("ENDERECO");
      modelo.setNumRows(0);
      tabelaConsultaTable.setModel(modelo);
      cpfTextFormatted.setEnabled(true);
   }
   
   private DefaultTableModel construirTabela(){
      DefaultTableModel modelo = new DefaultTableModel();
      modelo.addColumn("NOME");
      modelo.addColumn("CPF");
      modelo.addColumn("FONE");
      modelo.addColumn("ENDERECO");
      modelo.setNumRows(0);
      return modelo;
   }
   
   private void atualizarTabela(ArrayList<Cliente> clientes){
      
      //constrói um modelo da tabela. As inserções são feitas nos modelos, depois é atualizado na tabela parte grafica.
      DefaultTableModel modelo = construirTabela(); //limpa as linhas da tabela para nao ficar concatenando resultados anteriores.
      
      
      for(Cliente c  : clientes){
         //insere linha no modelo
         modelo.addRow(new Object[]{c.getNome(),c.getCpf(),c.getTelefone(),c.getEndereco()});
         
      }
      
      //atualiza tabela com um novo modelo carregado de dados.
      tabelaConsultaTable.setModel(modelo);//modelo é setado para tabela grafica
   }
   
   

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton backButton;
   private javax.swing.JPanel buttonsCadastroPanel;
   private javax.swing.JTabbedPane cadastroClienteTabbedPane;
   private javax.swing.JPanel cadastroPanel;
   private javax.swing.JPanel cadastroTextosPanel;
   private javax.swing.JPanel consultajPanel;
   private javax.swing.JRadioButton cpfRadioButton;
   private javax.swing.JFormattedTextField cpfTextFormatted;
   private javax.swing.JLabel cpfjLabel1;
   private javax.swing.JTextField enderecoText;
   private javax.swing.JLabel enderecojLabel;
   private javax.swing.ButtonGroup filtroButtonGroup;
   private javax.swing.JButton inserir_clienteButton;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JScrollPane jScrollPane3;
   private javax.swing.JButton nextButton;
   private javax.swing.JRadioButton nomeRadioButton;
   private javax.swing.JTextField nomeText;
   private javax.swing.JLabel nomejLabel;
   private javax.swing.JTextField pesquisaText;
   private javax.swing.JButton pesquisarButton;
   private javax.swing.JSpinner quantidade_de_resultadosSpinner;
   private javax.swing.JButton remover_clienteButton;
   private javax.swing.JButton salvar_clienteButton;
   private javax.swing.JTable tabelaConsultaTable;
   private javax.swing.JFormattedTextField telefoneTextFormatted;
   private javax.swing.JLabel telefonejLabel;
   // End of variables declaration//GEN-END:variables
}
