package interfaces;


import javax.swing.JOptionPane;
import persistencia.Bd;
import controle.*;
import dao.CategoriaDao;
import dao.FilmeDao;
import entidade.Filme;
import java.awt.Color;
import java.awt.Toolkit;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

public class JanelaVideoLocadora extends javax.swing.JFrame {

   public JanelaVideoLocadora() {
      
      Bd.abreConexao();
      initComponents();
      atulizarPrecoCategorias()  ;
      carregaIcone2();
      setExtendedState(MAXIMIZED_BOTH);
      atualizaListas();
      
   }
   private void atualizaListas(){
      DefaultListModel listaPromocao = new DefaultListModel();
      DefaultListModel listaLancamentos = new DefaultListModel();
      
      ArrayList<Filme> filmesPromocao = FilmeDao.getFilmesPorCategorias(Filme.Categoria.promoção);
      ArrayList<Filme> filmesLancamento = FilmeDao.getFilmesPorCategorias(Filme.Categoria.lançamento);
      
      for(Filme f : filmesPromocao){
         listaPromocao.addElement(f.getTitulo()+" ("+f.getAssunto()+")");
      }
      for(Filme f : filmesLancamento){
         listaLancamentos.addElement(f.getTitulo()+" ("+f.getAssunto()+")");
      }
      this.listaLancamentos.setModel(listaLancamentos);
      this.listaPromocao.setModel(listaPromocao);
   }
   
   public void carregaIcone(){
      URL url = this.getClass().getClassLoader().getResource("images/iconePipoca.png");
      ImageIcon icone = new ImageIcon(Toolkit.getDefaultToolkit().getImage(url));
      this.setIconImage(icone.getImage());
      
      
   }
   
   public final void carregaIcone2(){
      ImageIcon icone = new ImageIcon("images/iconePipoca.png");
      this.setIconImage(icone.getImage());
   }
   
   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jMenuItem1 = new javax.swing.JMenuItem();
      jMenuBar1 = new javax.swing.JMenuBar();
      jMenu1 = new javax.swing.JMenu();
      jMenu2 = new javax.swing.JMenu();
      painelSuperior = new javax.swing.JPanel();
      locarButton = new javax.swing.JButton();
      jSeparator5 = new javax.swing.JSeparator();
      reservarButton = new javax.swing.JButton();
      jSeparator6 = new javax.swing.JSeparator();
      filmesButton = new javax.swing.JButton();
      clientesButton = new javax.swing.JButton();
      jSeparator7 = new javax.swing.JSeparator();
      jSeparator8 = new javax.swing.JSeparator();
      sairButton = new javax.swing.JButton();
      painelEsquerdo = new javax.swing.JPanel();
      painelDireito = new javax.swing.JPanel();
      jSeparator9 = new javax.swing.JSeparator();
      painelInferior = new javax.swing.JPanel();
      valoresLabel = new javax.swing.JLabel();
      lancamentoLabel = new javax.swing.JLabel();
      catalagoLabel = new javax.swing.JLabel();
      promocaoLabel = new javax.swing.JLabel();
      painelDireitoAbas = new javax.swing.JPanel();
      abaTabbedPane = new javax.swing.JTabbedPane();
      painelLancamentos = new javax.swing.JPanel();
      jScrollPane1 = new javax.swing.JScrollPane();
      listaLancamentos = new javax.swing.JList();
      jPanel1 = new javax.swing.JPanel();
      jScrollPane2 = new javax.swing.JScrollPane();
      listaPromocao = new javax.swing.JList();
      principaljMenuBar = new javax.swing.JMenuBar();
      locacaoMenu = new javax.swing.JMenu();
      locarMenuItem = new javax.swing.JMenuItem();
      devolverMenuItem = new javax.swing.JMenuItem();
      consultarLocacoesMenuItem = new javax.swing.JMenuItem();
      jSeparator4 = new javax.swing.JPopupMenu.Separator();
      jSeparator3 = new javax.swing.JPopupMenu.Separator();
      sairMenuItem = new javax.swing.JMenuItem();
      jSeparator2 = new javax.swing.JPopupMenu.Separator();
      clienteMenu = new javax.swing.JMenu();
      cadastrar_clienteMenuItem = new javax.swing.JMenuItem();
      jSeparator1 = new javax.swing.JPopupMenu.Separator();
      filmeMenu = new javax.swing.JMenu();
      cadastrar_filmeMenuItem = new javax.swing.JMenuItem();
      reservaMenu = new javax.swing.JMenu();
      cadastrar_reservaMenuItem = new javax.swing.JMenuItem();
      copia_filmeMenu = new javax.swing.JMenu();
      cadastrar_copia_filmeMenuItem = new javax.swing.JMenuItem();
      preferenciasMenu = new javax.swing.JMenu();
      preco_por_categoriaMenuItem = new javax.swing.JMenuItem();
      ajudaMenu = new javax.swing.JMenu();
      sobreMenuItem = new javax.swing.JMenuItem();

      jMenuItem1.setText("jMenuItem1");

      jMenu1.setText("File");
      jMenuBar1.add(jMenu1);

      jMenu2.setText("Edit");
      jMenuBar1.add(jMenu2);

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setTitle("Video Locadora");
      setAutoRequestFocus(false);
      setBackground(java.awt.Color.white);
      setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
      addWindowListener(new java.awt.event.WindowAdapter() {
         public void windowClosed(java.awt.event.WindowEvent evt) {
            terminarSistema(evt);
         }
      });

      painelSuperior.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
      painelSuperior.setFocusable(false);

      locarButton.setBackground(new java.awt.Color(242, 241, 240));
      locarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/locar.png"))); // NOI18N
      locarButton.setToolTipText("");
      locarButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
      locarButton.setBorderPainted(false);
      locarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
      locarButton.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
      locarButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      locarButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            locarFilme(evt);
         }
      });

      jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
      jSeparator5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

      reservarButton.setBackground(new java.awt.Color(242, 241, 240));
      reservarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reservar.png"))); // NOI18N
      reservarButton.setToolTipText("");
      reservarButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
      reservarButton.setBorderPainted(false);
      reservarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
      reservarButton.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
      reservarButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      reservarButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            cadastrarReserva(evt);
         }
      });

      jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
      jSeparator6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

      filmesButton.setBackground(new java.awt.Color(242, 241, 240));
      filmesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/filmes.png"))); // NOI18N
      filmesButton.setToolTipText("");
      filmesButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
      filmesButton.setBorderPainted(false);
      filmesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
      filmesButton.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
      filmesButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      filmesButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            cadastrarFilme(evt);
         }
      });

      clientesButton.setBackground(new java.awt.Color(242, 241, 240));
      clientesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clientes.png"))); // NOI18N
      clientesButton.setToolTipText("");
      clientesButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
      clientesButton.setBorderPainted(false);
      clientesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
      clientesButton.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
      clientesButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      clientesButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            cadastrarCliente(evt);
         }
      });

      jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
      jSeparator7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

      jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
      jSeparator8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

      sairButton.setBackground(new java.awt.Color(242, 241, 240));
      sairButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sair.png"))); // NOI18N
      sairButton.setToolTipText("");
      sairButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
      sairButton.setBorderPainted(false);
      sairButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
      sairButton.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
      sairButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      sairButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            encerrarSistema(evt);
         }
      });

      javax.swing.GroupLayout painelEsquerdoLayout = new javax.swing.GroupLayout(painelEsquerdo);
      painelEsquerdo.setLayout(painelEsquerdoLayout);
      painelEsquerdoLayout.setHorizontalGroup(
         painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 0, Short.MAX_VALUE)
      );
      painelEsquerdoLayout.setVerticalGroup(
         painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 0, Short.MAX_VALUE)
      );

      javax.swing.GroupLayout painelDireitoLayout = new javax.swing.GroupLayout(painelDireito);
      painelDireito.setLayout(painelDireitoLayout);
      painelDireitoLayout.setHorizontalGroup(
         painelDireitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 0, Short.MAX_VALUE)
      );
      painelDireitoLayout.setVerticalGroup(
         painelDireitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 0, Short.MAX_VALUE)
      );

      jSeparator9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

      javax.swing.GroupLayout painelSuperiorLayout = new javax.swing.GroupLayout(painelSuperior);
      painelSuperior.setLayout(painelSuperiorLayout);
      painelSuperiorLayout.setHorizontalGroup(
         painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(painelSuperiorLayout.createSequentialGroup()
            .addGap(2, 2, 2)
            .addComponent(painelEsquerdo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(locarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(reservarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(clientesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(filmesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(sairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(painelDireito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
         .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.TRAILING)
      );
      painelSuperiorLayout.setVerticalGroup(
         painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(painelSuperiorLayout.createSequentialGroup()
            .addGroup(painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                  .addComponent(painelEsquerdo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(painelDireito, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addGroup(painelSuperiorLayout.createSequentialGroup()
                     .addContainerGap()
                     .addGroup(painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(locarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(reservarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(clientesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(filmesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
      );

      valoresLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
      valoresLabel.setText("VALORES");

      lancamentoLabel.setText("lançamentos:      R$");

      catalagoLabel.setText("catálagos:              R$");

      promocaoLabel.setText("promoção:             R$");

      javax.swing.GroupLayout painelInferiorLayout = new javax.swing.GroupLayout(painelInferior);
      painelInferior.setLayout(painelInferiorLayout);
      painelInferiorLayout.setHorizontalGroup(
         painelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelInferiorLayout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelInferiorLayout.createSequentialGroup()
                  .addComponent(valoresLabel)
                  .addGap(16, 16, 16))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(promocaoLabel)
                  .addComponent(catalagoLabel)
                  .addComponent(lancamentoLabel)))
            .addGap(62, 62, 62))
      );
      painelInferiorLayout.setVerticalGroup(
         painelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelInferiorLayout.createSequentialGroup()
            .addContainerGap(23, Short.MAX_VALUE)
            .addComponent(valoresLabel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lancamentoLabel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(catalagoLabel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(promocaoLabel)
            .addContainerGap())
      );

      painelDireitoAbas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

      abaTabbedPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
      abaTabbedPane.setTabPlacement(javax.swing.JTabbedPane.RIGHT);

      painelLancamentos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
      painelLancamentos.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

      listaLancamentos.setBackground(new java.awt.Color(242, 241, 240));
      listaLancamentos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
      listaLancamentos.setFont(new java.awt.Font("Purisa", 0, 18)); // NOI18N
      jScrollPane1.setViewportView(listaLancamentos);

      javax.swing.GroupLayout painelLancamentosLayout = new javax.swing.GroupLayout(painelLancamentos);
      painelLancamentos.setLayout(painelLancamentosLayout);
      painelLancamentosLayout.setHorizontalGroup(
         painelLancamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
      );
      painelLancamentosLayout.setVerticalGroup(
         painelLancamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
      );

      abaTabbedPane.addTab("lançamentos", painelLancamentos);

      listaPromocao.setBackground(new java.awt.Color(242, 241, 240));
      listaPromocao.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
      listaPromocao.setFont(new java.awt.Font("Purisa", 0, 18)); // NOI18N
      jScrollPane2.setViewportView(listaPromocao);

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
      );

      abaTabbedPane.addTab("promoção", jPanel1);

      javax.swing.GroupLayout painelDireitoAbasLayout = new javax.swing.GroupLayout(painelDireitoAbas);
      painelDireitoAbas.setLayout(painelDireitoAbasLayout);
      painelDireitoAbasLayout.setHorizontalGroup(
         painelDireitoAbasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(abaTabbedPane)
      );
      painelDireitoAbasLayout.setVerticalGroup(
         painelDireitoAbasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(abaTabbedPane)
      );

      principaljMenuBar.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

      locacaoMenu.setText("  Locadora");
      locacaoMenu.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

      locarMenuItem.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
      locarMenuItem.setText("Locar Filme");
      locarMenuItem.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            locarFilme(evt);
         }
      });
      locacaoMenu.add(locarMenuItem);

      devolverMenuItem.setBackground(new java.awt.Color(237, 232, 227));
      devolverMenuItem.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
      devolverMenuItem.setText("Devolver Filme");
      devolverMenuItem.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            devolverMenuItemActionPerformed(evt);
         }
      });
      locacaoMenu.add(devolverMenuItem);

      consultarLocacoesMenuItem.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
      consultarLocacoesMenuItem.setText("Consultar Locações");
      consultarLocacoesMenuItem.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            consultarLocacoes(evt);
         }
      });
      locacaoMenu.add(consultarLocacoesMenuItem);
      locacaoMenu.add(jSeparator4);
      locacaoMenu.add(jSeparator3);

      sairMenuItem.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
      sairMenuItem.setText("sair");
      sairMenuItem.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            sairMenuItemActionPerformed(evt);
         }
      });
      locacaoMenu.add(sairMenuItem);
      locacaoMenu.add(jSeparator2);

      principaljMenuBar.add(locacaoMenu);

      clienteMenu.setText("   Cliente   ");
      clienteMenu.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

      cadastrar_clienteMenuItem.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
      cadastrar_clienteMenuItem.setText("cadastrar cliente");
      cadastrar_clienteMenuItem.setToolTipText("");
      cadastrar_clienteMenuItem.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            cadastrarCliente(evt);
         }
      });
      clienteMenu.add(cadastrar_clienteMenuItem);
      clienteMenu.add(jSeparator1);

      principaljMenuBar.add(clienteMenu);

      filmeMenu.setText("Filme");
      filmeMenu.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

      cadastrar_filmeMenuItem.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
      cadastrar_filmeMenuItem.setText("cadastrar filme");
      cadastrar_filmeMenuItem.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            cadastrarFilme(evt);
         }
      });
      filmeMenu.add(cadastrar_filmeMenuItem);

      principaljMenuBar.add(filmeMenu);

      reservaMenu.setText("   Reserva   ");
      reservaMenu.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

      cadastrar_reservaMenuItem.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
      cadastrar_reservaMenuItem.setText("Cadastrar reserva");
      cadastrar_reservaMenuItem.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            cadastrarReserva(evt);
         }
      });
      reservaMenu.add(cadastrar_reservaMenuItem);

      principaljMenuBar.add(reservaMenu);

      copia_filmeMenu.setText("Cópia de filmes");
      copia_filmeMenu.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

      cadastrar_copia_filmeMenuItem.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
      cadastrar_copia_filmeMenuItem.setText("Cadastrar Cópia");
      cadastrar_copia_filmeMenuItem.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            cadastrarCopiaFilme(evt);
         }
      });
      copia_filmeMenu.add(cadastrar_copia_filmeMenuItem);

      principaljMenuBar.add(copia_filmeMenu);

      preferenciasMenu.setText("    Preferências   ");
      preferenciasMenu.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

      preco_por_categoriaMenuItem.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
      preco_por_categoriaMenuItem.setText("Preço por Categoria");
      preco_por_categoriaMenuItem.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            precoPorCategoriaPressMenuItem(evt);
         }
      });
      preferenciasMenu.add(preco_por_categoriaMenuItem);

      principaljMenuBar.add(preferenciasMenu);

      ajudaMenu.setText("   ajuda   ");
      ajudaMenu.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

      sobreMenuItem.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
      sobreMenuItem.setText("sobre");
      sobreMenuItem.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            sobreMenuItemActionPerformed(evt);
         }
      });
      ajudaMenu.add(sobreMenuItem);

      principaljMenuBar.add(ajudaMenu);

      setJMenuBar(principaljMenuBar);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(painelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addComponent(painelInferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(700, 700, 700)
            .addComponent(painelDireitoAbas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(painelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(painelDireitoAbas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(painelInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
      );

      setSize(new java.awt.Dimension(1093, 606));
      setLocationRelativeTo(null);
   }// </editor-fold>//GEN-END:initComponents

   private void sobreMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobreMenuItemActionPerformed
      new JanelaSobre().setVisible(true);
   }//GEN-LAST:event_sobreMenuItemActionPerformed

    private void terminarSistema(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_terminarSistema
       Bd.fechaConexao();
       System.exit(1);
    }//GEN-LAST:event_terminarSistema

   private void cadastrarCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarCliente
      new ControladorCadastroCliente();
      
   }//GEN-LAST:event_cadastrarCliente

   private void cadastrarFilme(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFilme
      new ControladorCadastroFilme();
      atualizaListas();
   }//GEN-LAST:event_cadastrarFilme

   private void cadastrarReserva(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarReserva
      new ControladorReservas();
   }//GEN-LAST:event_cadastrarReserva

   private void cadastrarCopiaFilme(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarCopiaFilme
      new ControladorCopiaFilme();
   }//GEN-LAST:event_cadastrarCopiaFilme

   private void sairMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairMenuItemActionPerformed
      terminarSistema(null);
   }//GEN-LAST:event_sairMenuItemActionPerformed

   private void locarFilme(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locarFilme
     new ControladorLocarCopias(); 
   }//GEN-LAST:event_locarFilme

   private void precoPorCategoriaPressMenuItem(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precoPorCategoriaPressMenuItem
      new JanelaCategoria().setVisible(true);
      atulizarPrecoCategorias();
   }//GEN-LAST:event_precoPorCategoriaPressMenuItem

    private void devolverMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolverMenuItemActionPerformed
      new JanelaDevolverCopiasFilmes().setVisible(true);
    }//GEN-LAST:event_devolverMenuItemActionPerformed

   private void encerrarSistema(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encerrarSistema
      terminarSistema(null);
   }//GEN-LAST:event_encerrarSistema

   private void consultarLocacoes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarLocacoes
      new JanelaConsultarLocacoes().setVisible(true);
   }//GEN-LAST:event_consultarLocacoes
   
   /**
    * @param args the command line arguments
    */
   private void informaServicoIndisponivel() {
      JOptionPane.showMessageDialog(this, "Serviço indisponível!", "Informação", JOptionPane.INFORMATION_MESSAGE);
   }
   
   private void atulizarPrecoCategorias(){
      promocaoLabel.setText("promoção:             R$"+CategoriaDao.getCategoria(Filme.Categoria.promoção).getValor()+"0");
      catalagoLabel.setText("catálagos:              R$"+CategoriaDao.getCategoria(Filme.Categoria.catálogo).getValor()+"0");
      lancamentoLabel.setText("lançamentos:      R$"+CategoriaDao.getCategoria(Filme.Categoria.lançamento).getValor()+"0");
   }
           
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("GTK+".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(JanelaVideoLocadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(JanelaVideoLocadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(JanelaVideoLocadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(JanelaVideoLocadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
        //</editor-fold>

      /* Create and display the form */
      
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new JanelaVideoLocadora().setVisible(true);
            
         }
      });
   }
   public static void inserir_só_letrasEVT(java.awt.event.KeyEvent evt) {                                      
      String caracter_nao_aceito="0123456789@!#$%¨&*(){}[]+=_-§\"/?;:.>,<\\|";
      if(caracter_nao_aceito.contains(evt.getKeyChar()+"")){
         evt.consume();
      }
   } 

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JTabbedPane abaTabbedPane;
   private javax.swing.JMenu ajudaMenu;
   private javax.swing.JMenuItem cadastrar_clienteMenuItem;
   private javax.swing.JMenuItem cadastrar_copia_filmeMenuItem;
   private javax.swing.JMenuItem cadastrar_filmeMenuItem;
   private javax.swing.JMenuItem cadastrar_reservaMenuItem;
   private javax.swing.JLabel catalagoLabel;
   private javax.swing.JMenu clienteMenu;
   private javax.swing.JButton clientesButton;
   private javax.swing.JMenuItem consultarLocacoesMenuItem;
   private javax.swing.JMenu copia_filmeMenu;
   private javax.swing.JMenuItem devolverMenuItem;
   private javax.swing.JMenu filmeMenu;
   private javax.swing.JButton filmesButton;
   private javax.swing.JMenu jMenu1;
   private javax.swing.JMenu jMenu2;
   private javax.swing.JMenuBar jMenuBar1;
   private javax.swing.JMenuItem jMenuItem1;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JPopupMenu.Separator jSeparator1;
   private javax.swing.JPopupMenu.Separator jSeparator2;
   private javax.swing.JPopupMenu.Separator jSeparator3;
   private javax.swing.JPopupMenu.Separator jSeparator4;
   private javax.swing.JSeparator jSeparator5;
   private javax.swing.JSeparator jSeparator6;
   private javax.swing.JSeparator jSeparator7;
   private javax.swing.JSeparator jSeparator8;
   private javax.swing.JSeparator jSeparator9;
   private javax.swing.JLabel lancamentoLabel;
   private javax.swing.JList listaLancamentos;
   private javax.swing.JList listaPromocao;
   private javax.swing.JMenu locacaoMenu;
   private javax.swing.JButton locarButton;
   private javax.swing.JMenuItem locarMenuItem;
   private javax.swing.JPanel painelDireito;
   private javax.swing.JPanel painelDireitoAbas;
   private javax.swing.JPanel painelEsquerdo;
   private javax.swing.JPanel painelInferior;
   private javax.swing.JPanel painelLancamentos;
   private javax.swing.JPanel painelSuperior;
   private javax.swing.JMenuItem preco_por_categoriaMenuItem;
   private javax.swing.JMenu preferenciasMenu;
   private javax.swing.JMenuBar principaljMenuBar;
   private javax.swing.JLabel promocaoLabel;
   private javax.swing.JMenu reservaMenu;
   private javax.swing.JButton reservarButton;
   private javax.swing.JButton sairButton;
   private javax.swing.JMenuItem sairMenuItem;
   private javax.swing.JMenuItem sobreMenuItem;
   private javax.swing.JLabel valoresLabel;
   // End of variables declaration//GEN-END:variables
}
