package interfaces;

import controle.ControladorCadastroFilme;
import entidade.Filme;
import entidade.Visao;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author juarez
 */


public class JanelaCadastroFilmes extends javax.swing.JDialog {
   private ControladorCadastroFilme controlador;
   private static enum Estado {inserindo, editando};
   Estado estado = null;
   DefaultListModel modeloTemporario = new DefaultListModel();
   
   
   /**
    * Creates new form JanelaCadastroFilmes
    * @param controlador
    */
   public JanelaCadastroFilmes(ControladorCadastroFilme controlador) {
      super(new javax.swing.JFrame(), true);
      estado = Estado.inserindo;
      this.controlador = controlador;
      initComponents();
      inicializarListaFilmes();
      inicializarCategoriaFilmes();
      limpaCamposText();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      categoriaButtonGroup = new javax.swing.ButtonGroup();
      guia_cadastro_filmeTabbedPane = new javax.swing.JTabbedPane();
      cadastroPanel = new javax.swing.JPanel();
      filmesLabel = new javax.swing.JLabel();
      jScrollPane2 = new javax.swing.JScrollPane();
      filmes_cadastradosList = new javax.swing.JList();
      editar_cadastro_filmeButton = new javax.swing.JButton();
      consultaPanel = new javax.swing.JPanel();
      idLabel = new javax.swing.JLabel();
      tituloTextField = new javax.swing.JTextField();
      assuntoComboBox = new javax.swing.JComboBox();
      assuntoLabel = new javax.swing.JLabel();
      tituloLabel = new javax.swing.JLabel();
      idTextField = new javax.swing.JTextField();
      oscarCheckBox = new javax.swing.JCheckBox();
      ultimas_consultasLabel = new javax.swing.JLabel();
      jScrollPane3 = new javax.swing.JScrollPane();
      ultimas_consultasTextArea = new javax.swing.JTextArea();
      gravarButton = new javax.swing.JButton();
      removerButton = new javax.swing.JButton();
      inserir_filmeButton = new javax.swing.JButton();
      limpar_ultimas_consultarButton = new javax.swing.JButton();
      categoria_grupoPanel = new javax.swing.JPanel();
      categoriaLabel = new javax.swing.JLabel();
      lancamentoRadioButton = new javax.swing.JRadioButton();
      promocaoRadioButton = new javax.swing.JRadioButton();
      catalogoRadioButton = new javax.swing.JRadioButton();
      jScrollPane1 = new javax.swing.JScrollPane();
      filmes_adc_recentementeList = new javax.swing.JList();
      ultimos_filmesLabel = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setTitle("Cadastro de Filmes");
      setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

      guia_cadastro_filmeTabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
      guia_cadastro_filmeTabbedPane.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
      guia_cadastro_filmeTabbedPane.setPreferredSize(new java.awt.Dimension(800, 600));

      filmesLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
      filmesLabel.setText("Filmes Cadastrados");

      jScrollPane2.setViewportView(filmes_cadastradosList);
      filmes_cadastradosList.getAccessibleContext().setAccessibleName("lista_filmesList");

      editar_cadastro_filmeButton.setText("editar");
      editar_cadastro_filmeButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            consultaFilme(evt);
         }
      });

      javax.swing.GroupLayout cadastroPanelLayout = new javax.swing.GroupLayout(cadastroPanel);
      cadastroPanel.setLayout(cadastroPanelLayout);
      cadastroPanelLayout.setHorizontalGroup(
         cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroPanelLayout.createSequentialGroup()
            .addGap(78, 78, 78)
            .addComponent(filmesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
            .addGap(302, 302, 302)
            .addComponent(editar_cadastro_filmeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
            .addGap(50, 50, 50))
         .addGroup(cadastroPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane2)
            .addContainerGap())
      );
      cadastroPanelLayout.setVerticalGroup(
         cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(cadastroPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(editar_cadastro_filmeButton)
               .addComponent(filmesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(7, 7, 7)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
            .addContainerGap())
      );

      guia_cadastro_filmeTabbedPane.addTab("    Consulta    ", cadastroPanel);

      idLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
      idLabel.setText("ID");

      assuntoComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "aventura", "comédia", "drama", "faroeste", "ficção", "guerra", "romance", "suspense", "terror" }));

      assuntoLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
      assuntoLabel.setText("Assunto");

      tituloLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
      tituloLabel.setText("Título");

      idTextField.setEnabled(false);

      oscarCheckBox.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
      oscarCheckBox.setText("Oscar melhor filme");

      ultimas_consultasLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
      ultimas_consultasLabel.setText("Últimas Consultas:");

      ultimas_consultasTextArea.setColumns(20);
      ultimas_consultasTextArea.setRows(5);
      jScrollPane3.setViewportView(ultimas_consultasTextArea);

      gravarButton.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
      gravarButton.setText("Gravar");
      gravarButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            gravarFilme(evt);
         }
      });

      removerButton.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
      removerButton.setText("Remover");
      removerButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            removerFilme(evt);
         }
      });

      inserir_filmeButton.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
      inserir_filmeButton.setText("+");
      inserir_filmeButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            inserir_filme(evt);
         }
      });

      limpar_ultimas_consultarButton.setText("limpar");
      limpar_ultimas_consultarButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            limpar_ultimas_consultarButtonActionPerformed(evt);
         }
      });

      categoriaLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
      categoriaLabel.setText("Categoria");

      categoriaButtonGroup.add(lancamentoRadioButton);
      lancamentoRadioButton.setSelected(true);
      lancamentoRadioButton.setText("lançamento");

      categoriaButtonGroup.add(promocaoRadioButton);
      promocaoRadioButton.setText("promoção");

      categoriaButtonGroup.add(catalogoRadioButton);
      catalogoRadioButton.setText("catálogo");

      javax.swing.GroupLayout categoria_grupoPanelLayout = new javax.swing.GroupLayout(categoria_grupoPanel);
      categoria_grupoPanel.setLayout(categoria_grupoPanelLayout);
      categoria_grupoPanelLayout.setHorizontalGroup(
         categoria_grupoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, categoria_grupoPanelLayout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(categoriaLabel)
            .addGap(33, 33, 33)
            .addComponent(lancamentoRadioButton)
            .addGap(30, 30, 30)
            .addComponent(promocaoRadioButton)
            .addGap(30, 30, 30)
            .addComponent(catalogoRadioButton)
            .addContainerGap())
      );
      categoria_grupoPanelLayout.setVerticalGroup(
         categoria_grupoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(categoria_grupoPanelLayout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(categoria_grupoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(categoriaLabel)
               .addComponent(lancamentoRadioButton)
               .addComponent(promocaoRadioButton)
               .addComponent(catalogoRadioButton)))
      );

      filmes_adc_recentementeList.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            filmes_adc_recentementeListMouseClicked(evt);
         }
      });
      jScrollPane1.setViewportView(filmes_adc_recentementeList);

      ultimos_filmesLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
      ultimos_filmesLabel.setText("Ultimos filmes adicionados:");

      javax.swing.GroupLayout consultaPanelLayout = new javax.swing.GroupLayout(consultaPanel);
      consultaPanel.setLayout(consultaPanelLayout);
      consultaPanelLayout.setHorizontalGroup(
         consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(consultaPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addGroup(consultaPanelLayout.createSequentialGroup()
                  .addGap(12, 12, 12)
                  .addComponent(jScrollPane3))
               .addComponent(categoria_grupoPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(javax.swing.GroupLayout.Alignment.LEADING, consultaPanelLayout.createSequentialGroup()
                  .addGap(14, 14, 14)
                  .addGroup(consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(consultaPanelLayout.createSequentialGroup()
                        .addGroup(consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                           .addComponent(idLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(tituloLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(tituloTextField)
                           .addGroup(consultaPanelLayout.createSequentialGroup()
                              .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(493, 493, 493))))
                     .addComponent(ultimos_filmesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jScrollPane1)
                     .addGroup(consultaPanelLayout.createSequentialGroup()
                        .addComponent(assuntoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(assuntoComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(273, 273, 273))))
               .addGroup(javax.swing.GroupLayout.Alignment.LEADING, consultaPanelLayout.createSequentialGroup()
                  .addGap(12, 12, 12)
                  .addGroup(consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(consultaPanelLayout.createSequentialGroup()
                        .addGroup(consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultaPanelLayout.createSequentialGroup()
                              .addGap(149, 149, 149)
                              .addComponent(gravarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addGap(39, 39, 39)
                              .addComponent(inserir_filmeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(39, 39, 39)
                              .addComponent(removerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addGap(84, 84, 84))
                           .addComponent(oscarCheckBox))
                        .addGap(2, 2, 2))
                     .addGroup(consultaPanelLayout.createSequentialGroup()
                        .addComponent(ultimas_consultasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(limpar_ultimas_consultarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGap(75, 75, 75))
      );
      consultaPanelLayout.setVerticalGroup(
         consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultaPanelLayout.createSequentialGroup()
            .addGap(45, 45, 45)
            .addComponent(ultimos_filmesLabel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(consultaPanelLayout.createSequentialGroup()
                  .addGap(7, 7, 7)
                  .addComponent(idLabel))
               .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(tituloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(tituloLabel))
            .addGap(18, 18, 18)
            .addGroup(consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(assuntoLabel)
               .addComponent(assuntoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(categoria_grupoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(oscarCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(ultimas_consultasLabel)
               .addComponent(limpar_ultimas_consultarButton))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
            .addGap(18, 18, 18)
            .addGroup(consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(gravarButton)
               .addComponent(removerButton)
               .addComponent(inserir_filmeButton))
            .addContainerGap())
      );

      guia_cadastro_filmeTabbedPane.addTab("     Cadastro    ", consultaPanel);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(guia_cadastro_filmeTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 843, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(guia_cadastro_filmeTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
      );

      pack();
      setLocationRelativeTo(null);
   }// </editor-fold>//GEN-END:initComponents
   
   private void inserir_filme(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserir_filme
      estado = Estado.inserindo;
      limpaCamposText();
   }//GEN-LAST:event_inserir_filme

   private void gravarFilme(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gravarFilme
      if(isCamposVazio()){
         JOptionPane.showMessageDialog(null, "Preencha todos os campos antes de gravar!");
         return;
      }
      
      //Cria objeto filme com sequencial nulo
      Filme filme = new Filme();
      filme.setTitulo(tituloTextField.getText());
      filme.setAssunto(assuntoComboBox.getSelectedItem().toString());
      filme.setOscar_melhor_filme(oscarCheckBox.isSelected());
      filme.setCategoria(categoriaButtonGroup.getSelection().getActionCommand());
      //fim
      
      if(estado==Estado.inserindo){
         if(controlador.inserir(filme)){
            idTextField.setText(Integer.toString(controlador.getUltimoSequencial()));
            inicializarListaFilmes();//atualiza a lista de filmes
            estado = Estado.editando;
            filmes_cadastradosList.setSelectedIndex(filmes_cadastradosList.getLastVisibleIndex()); //posiciona na ultimo indice
            atualiza_lista_ultimosFilmes(filme);
            return;
         }
      }
      if(estado==Estado.editando){
         filme.setId(Integer.parseInt(idTextField.getText()));
         if(controlador.alterar(filme)){ 
            inicializarListaFilmes();//atualiza a lista de filmes
            estado = Estado.editando;
            return;
         }
      }
   }//GEN-LAST:event_gravarFilme

   private void atualiza_lista_ultimosFilmes(Filme filme){
      modeloTemporario.addElement(filme);
      filmes_adc_recentementeList.setModel(modeloTemporario);
   }
   
   private void removerFilme(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerFilme
      if(estado==Estado.editando){
         if(controlador.deletar(Integer.parseInt(idTextField.getText()))){
            limpaCamposText();
            estado = Estado.inserindo;
         }
      }
      
      inicializarListaFilmes();//atualiza a lista de filmes
   }//GEN-LAST:event_removerFilme

   private void limpar_ultimas_consultarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpar_ultimas_consultarButtonActionPerformed

      ultimas_consultasTextArea.setText("");
   }//GEN-LAST:event_limpar_ultimas_consultarButtonActionPerformed

   private void consultaFilme(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaFilme
      
      int linhaSelecionada = filmes_cadastradosList.getSelectedIndex();
      
      
      if(linhaSelecionada>=0){
         estado= Estado.editando;
         
         Visao<Integer> filmeSelecionado = new Visao<Integer>();
         filmeSelecionado = (Visao)filmes_cadastradosList.getSelectedValue();
         Filme filme = controlador.getFilme(filmeSelecionado.getChave());
         
         //inicializa textFields da aba de cadastro
         idTextField.setText(Integer.toString(filme.getId()));
         tituloTextField.setText(filme.getTitulo());
         if(filme.getCategoria()==Filme.Categoria.lançamento)
            lancamentoRadioButton.setSelected(true);
         if(filme.getCategoria()==Filme.Categoria.promoção)
            promocaoRadioButton.setSelected(true);
         if(filme.getCategoria()==Filme.Categoria.catálogo)
            catalogoRadioButton.setSelected(true);
         for(int i=0;i<assuntoComboBox.getItemCount();i++){
            //compara item do combobox com o assunto do filme, se forem iguais entao deixe selecionado o item
            assuntoComboBox.setSelectedIndex(i);
            if(assuntoComboBox.getSelectedItem().toString().compareToIgnoreCase(filme.getAssunto()+"")==0){
               break;
            }
         }
         oscarCheckBox.setSelected(filme.isOscar_melhor_filme());
         
         SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy hh:mm");
         String textoUltimaConsulta = sdf.format(new Date())+":\n"+filme.toString()+ultimas_consultasTextArea.getText();
         ultimas_consultasTextArea.setText(textoUltimaConsulta);
         //trocar de aba
         guia_cadastro_filmeTabbedPane.setSelectedIndex(1);
      }
   }//GEN-LAST:event_consultaFilme

   private void filmes_adc_recentementeListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filmes_adc_recentementeListMouseClicked
      Filme filme = (Filme)filmes_adc_recentementeList.getSelectedValue();
      
   }//GEN-LAST:event_filmes_adc_recentementeListMouseClicked
   
   private boolean isCamposVazio(){
      return tituloTextField.getText().isEmpty() || assuntoComboBox.getSelectedIndex()==-1;
   } 
   
   private void limpaCamposText(){
      idTextField.setText("");
      tituloTextField.setText("");
      assuntoComboBox.setSelectedIndex(-1);
      lancamentoRadioButton.setSelected(true);
      oscarCheckBox.setSelected(false);
   }
   
   private void inicializarCategoriaFilmes(){
      promocaoRadioButton.setActionCommand("promoção");
      catalogoRadioButton.setActionCommand("catálogo");
      lancamentoRadioButton.setActionCommand("lançamento");
      
   }
   
   private void inicializarListaFilmes(){
      
      Vector<Visao<Integer>> visoes = visoes = controlador.getVisoes(); //Recebe um vetor com todas as visoes de filmes
      DefaultListModel modelo = new DefaultListModel();
      
      for(Visao<Integer> visao : visoes){
         modelo.addElement(visao);
      }
      filmes_cadastradosList.setModel(modelo);
      
   }
   
   
   

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JComboBox assuntoComboBox;
   private javax.swing.JLabel assuntoLabel;
   private javax.swing.JPanel cadastroPanel;
   private javax.swing.JRadioButton catalogoRadioButton;
   private javax.swing.ButtonGroup categoriaButtonGroup;
   private javax.swing.JLabel categoriaLabel;
   private javax.swing.JPanel categoria_grupoPanel;
   private javax.swing.JPanel consultaPanel;
   private javax.swing.JButton editar_cadastro_filmeButton;
   private javax.swing.JLabel filmesLabel;
   private javax.swing.JList filmes_adc_recentementeList;
   private javax.swing.JList filmes_cadastradosList;
   private javax.swing.JButton gravarButton;
   private javax.swing.JTabbedPane guia_cadastro_filmeTabbedPane;
   private javax.swing.JLabel idLabel;
   private javax.swing.JTextField idTextField;
   private javax.swing.JButton inserir_filmeButton;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JScrollPane jScrollPane3;
   private javax.swing.JRadioButton lancamentoRadioButton;
   private javax.swing.JButton limpar_ultimas_consultarButton;
   private javax.swing.JCheckBox oscarCheckBox;
   private javax.swing.JRadioButton promocaoRadioButton;
   private javax.swing.JButton removerButton;
   private javax.swing.JLabel tituloLabel;
   private javax.swing.JTextField tituloTextField;
   private javax.swing.JLabel ultimas_consultasLabel;
   private javax.swing.JTextArea ultimas_consultasTextArea;
   private javax.swing.JLabel ultimos_filmesLabel;
   // End of variables declaration//GEN-END:variables
}
